default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hello_rails_backend_development
  port: 5433

test:
  <<: *default
  database: hello_rails_backend_test
  port: 5433

production:
  <<: *default
  database: hello_rails_backend_production
  username: hello_rails_backend
  password: <%= ENV["HELLO_RAILS_BACKEND_DATABASE_PASSWORD"] %>
